# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coordinate7.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1762, 754)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 1131, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_2)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton_connection = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_connection.setObjectName("pushButton_connection")
        self.horizontalLayout.addWidget(self.pushButton_connection)
        self.pushButton_resetzero = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_resetzero.setObjectName("pushButton_resetzero")
        self.horizontalLayout.addWidget(self.pushButton_resetzero)
        self.pushButton_replace = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_replace.setObjectName("pushButton_replace")
        self.horizontalLayout.addWidget(self.pushButton_replace)
        self.pushButton_stop = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1131, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_4.addWidget(self.pushButton_14)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.horizontalLayoutWidget_4)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 170, 961, 491))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 951, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(0, 80, 161, 171))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 160, 135))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_2.addWidget(self.pushButton_15)
        self.pushButton_17 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_2.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_2.addWidget(self.pushButton_18)
        self.pushButton_16 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_2.addWidget(self.pushButton_16)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.textEdit = QtWidgets.QTextEdit(self.page_2)
        self.textEdit.setGeometry(QtCore.QRect(-390, 160, 104, 87))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_2)
        self.textEdit_2.setGeometry(QtCore.QRect(3, -4, 461, 481))
        self.textEdit_2.setStyleSheet("")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(992, 183, 55, 50))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(992, 127, 55, 49))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(992, 240, 55, 49))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(992, 70, 55, 50))
        self.label_19.setObjectName("label_19")
        self.tabWidget_CJ = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget_CJ.setGeometry(QtCore.QRect(470, 0, 501, 461))
        self.tabWidget_CJ.setStyleSheet("color: rgb(36, 207, 24);\n"
"selection-color: rgb(255, 170, 0);\n"
"background-color: rgb(0, 85, 127);")
        self.tabWidget_CJ.setMovable(False)
        self.tabWidget_CJ.setObjectName("tabWidget_CJ")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_run_coordinate = QtWidgets.QPushButton(self.tab)
        self.pushButton_run_coordinate.setGeometry(QtCore.QRect(10, 10, 118, 28))
        self.pushButton_run_coordinate.setObjectName("pushButton_run_coordinate")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(90, 270, 331, 91))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_Speed_name_coordinate = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_Speed_name_coordinate.setObjectName("label_Speed_name_coordinate")
        self.gridLayout_4.addWidget(self.label_Speed_name_coordinate, 0, 0, 1, 1)
        self.label_Speed_num_coordinate = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_Speed_num_coordinate.setObjectName("label_Speed_num_coordinate")
        self.gridLayout_4.addWidget(self.label_Speed_num_coordinate, 0, 1, 1, 1)
        self.slider_Speed_coordinate = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.slider_Speed_coordinate.setMinimum(25)
        self.slider_Speed_coordinate.setMaximum(500)
        self.slider_Speed_coordinate.setSingleStep(5)
        self.slider_Speed_coordinate.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Speed_coordinate.setObjectName("slider_Speed_coordinate")
        self.gridLayout_4.addWidget(self.slider_Speed_coordinate, 0, 3, 1, 1)
        self.pushButton_speedsetting_coordinate = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_speedsetting_coordinate.setObjectName("pushButton_speedsetting_coordinate")
        self.gridLayout_4.addWidget(self.pushButton_speedsetting_coordinate, 0, 4, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 40, 441, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_r = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_r.setMinimum(-99.0)
        self.doubleSpinBox_r.setObjectName("doubleSpinBox_r")
        self.gridLayout.addWidget(self.doubleSpinBox_r, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        self.pushButton_zup = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_zup.setObjectName("pushButton_zup")
        self.gridLayout.addWidget(self.pushButton_zup, 2, 3, 1, 1)
        self.pushButton_yup = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_yup.setObjectName("pushButton_yup")
        self.gridLayout.addWidget(self.pushButton_yup, 1, 3, 1, 1)
        self.pushButton_ydown = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_ydown.setObjectName("pushButton_ydown")
        self.gridLayout.addWidget(self.pushButton_ydown, 1, 4, 1, 1)
        self.pushButton_xdown = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_xdown.setObjectName("pushButton_xdown")
        self.gridLayout.addWidget(self.pushButton_xdown, 0, 4, 1, 1)
        self.pushButton_xup = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_xup.setObjectName("pushButton_xup")
        self.gridLayout.addWidget(self.pushButton_xup, 0, 3, 1, 1)
        self.pushButton_rup = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_rup.setObjectName("pushButton_rup")
        self.gridLayout.addWidget(self.pushButton_rup, 3, 3, 1, 1)
        self.label_x = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_x.setObjectName("label_x")
        self.gridLayout.addWidget(self.label_x, 0, 0, 1, 1)
        self.label_y = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_y.setObjectName("label_y")
        self.gridLayout.addWidget(self.label_y, 1, 0, 1, 1)
        self.label_r = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_r.setObjectName("label_r")
        self.gridLayout.addWidget(self.label_r, 3, 0, 1, 1)
        self.pushButton_zdown = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_zdown.setObjectName("pushButton_zdown")
        self.gridLayout.addWidget(self.pushButton_zdown, 2, 4, 1, 1)
        self.pushButton_rdown = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_rdown.setObjectName("pushButton_rdown")
        self.gridLayout.addWidget(self.pushButton_rdown, 3, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 2, 1, 1)
        self.label_z = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_z.setObjectName("label_z")
        self.gridLayout.addWidget(self.label_z, 2, 0, 1, 1)
        self.doubleSpinBox_x = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_x.setDecimals(2)
        self.doubleSpinBox_x.setMinimum(-99.0)
        self.doubleSpinBox_x.setObjectName("doubleSpinBox_x")
        self.gridLayout.addWidget(self.doubleSpinBox_x, 0, 1, 1, 1)
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_y.setMinimum(-99.0)
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.gridLayout.addWidget(self.doubleSpinBox_y, 1, 1, 1, 1)
        self.doubleSpinBox_z = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_z.setMinimum(-99.0)
        self.doubleSpinBox_z.setObjectName("doubleSpinBox_z")
        self.gridLayout.addWidget(self.doubleSpinBox_z, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 2, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 370, 160, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_step_coordinate = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_step_coordinate.setObjectName("label_step_coordinate")
        self.horizontalLayout_2.addWidget(self.label_step_coordinate)
        self.doubleSpinBox_step_coordinate = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.doubleSpinBox_step_coordinate.setMinimum(-99.0)
        self.doubleSpinBox_step_coordinate.setSingleStep(5.0)
        self.doubleSpinBox_step_coordinate.setObjectName("doubleSpinBox_step_coordinate")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_step_coordinate)
        self.tabWidget_CJ.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_run_joint = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_run_joint.setGeometry(QtCore.QRect(10, 10, 118, 28))
        self.pushButton_run_joint.setObjectName("pushButton_run_joint")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(40, 40, 441, 241))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox_j4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_j4.setMinimum(-99.0)
        self.doubleSpinBox_j4.setObjectName("doubleSpinBox_j4")
        self.gridLayout_3.addWidget(self.doubleSpinBox_j4, 3, 1, 1, 1)
        self.doubleSpinBox_j2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_j2.setMinimum(-99.0)
        self.doubleSpinBox_j2.setProperty("value", 0.0)
        self.doubleSpinBox_j2.setObjectName("doubleSpinBox_j2")
        self.gridLayout_3.addWidget(self.doubleSpinBox_j2, 1, 1, 1, 1)
        self.doubleSpinBox_j3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_j3.setMinimum(-99.0)
        self.doubleSpinBox_j3.setObjectName("doubleSpinBox_j3")
        self.gridLayout_3.addWidget(self.doubleSpinBox_j3, 2, 1, 1, 1)
        self.pushButton_J3down = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_J3down.setObjectName("pushButton_J3down")
        self.gridLayout_3.addWidget(self.pushButton_J3down, 2, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 3, 2, 1, 1)
        self.label_J2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_J2.setObjectName("label_J2")
        self.gridLayout_3.addWidget(self.label_J2, 1, 0, 1, 1)
        self.label_J3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_J3.setObjectName("label_J3")
        self.gridLayout_3.addWidget(self.label_J3, 2, 0, 1, 1)
        self.pushButton_J2down = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_J2down.setObjectName("pushButton_J2down")
        self.gridLayout_3.addWidget(self.pushButton_J2down, 1, 4, 1, 1)
        self.pushButton_J1up = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_J1up.setObjectName("pushButton_J1up")
        self.gridLayout_3.addWidget(self.pushButton_J1up, 0, 3, 1, 1)
        self.pushButton_J2up = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_J2up.setObjectName("pushButton_J2up")
        self.gridLayout_3.addWidget(self.pushButton_J2up, 1, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 2, 2, 1, 1)
        self.pushButton_J4down = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_J4down.setObjectName("pushButton_J4down")
        self.gridLayout_3.addWidget(self.pushButton_J4down, 3, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 1, 2, 1, 1)
        self.pushButton_J3up = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_J3up.setObjectName("pushButton_J3up")
        self.gridLayout_3.addWidget(self.pushButton_J3up, 2, 3, 1, 1)
        self.label_J1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_J1.setObjectName("label_J1")
        self.gridLayout_3.addWidget(self.label_J1, 0, 0, 1, 1)
        self.label_J4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_J4.setObjectName("label_J4")
        self.gridLayout_3.addWidget(self.label_J4, 3, 0, 1, 1)
        self.pushButton_J1down = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_J1down.setObjectName("pushButton_J1down")
        self.gridLayout_3.addWidget(self.pushButton_J1down, 0, 4, 1, 1)
        self.pushButton_J4up = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_J4up.setObjectName("pushButton_J4up")
        self.gridLayout_3.addWidget(self.pushButton_J4up, 3, 3, 1, 1)
        self.doubleSpinBox_j1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.doubleSpinBox_j1.setMinimum(-99.0)
        self.doubleSpinBox_j1.setObjectName("doubleSpinBox_j1")
        self.gridLayout_3.addWidget(self.doubleSpinBox_j1, 0, 1, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(90, 270, 331, 91))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_Speed_name_joint = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_Speed_name_joint.setObjectName("label_Speed_name_joint")
        self.gridLayout_5.addWidget(self.label_Speed_name_joint, 0, 0, 1, 1)
        self.label_Speed_num_joint = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_Speed_num_joint.setObjectName("label_Speed_num_joint")
        self.gridLayout_5.addWidget(self.label_Speed_num_joint, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 0, 2, 1, 1)
        self.slider_Speed_joint = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.slider_Speed_joint.setMinimum(25)
        self.slider_Speed_joint.setMaximum(500)
        self.slider_Speed_joint.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Speed_joint.setObjectName("slider_Speed_joint")
        self.gridLayout_5.addWidget(self.slider_Speed_joint, 0, 3, 1, 1)
        self.pushButton_speedsetting_joint = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_speedsetting_joint.setObjectName("pushButton_speedsetting_joint")
        self.gridLayout_5.addWidget(self.pushButton_speedsetting_joint, 0, 4, 1, 1)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(40, 370, 160, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_step_joint = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_step_joint.setObjectName("label_step_joint")
        self.horizontalLayout_5.addWidget(self.label_step_joint)
        self.doubleSpinBox_step_joint = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_5)
        self.doubleSpinBox_step_joint.setMinimum(-99.0)
        self.doubleSpinBox_step_joint.setSingleStep(5.0)
        self.doubleSpinBox_step_joint.setObjectName("doubleSpinBox_step_joint")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_step_joint)
        self.tabWidget_CJ.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.page_2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 171, 161, 471))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.doubleSpinBox_delay = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_delay.setGeometry(QtCore.QRect(90, 120, 277, 24))
        self.doubleSpinBox_delay.setMinimum(-99.0)
        self.doubleSpinBox_delay.setObjectName("doubleSpinBox_delay")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 130, 72, 15))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1140, 0, 611, 611))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_readline = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_readline.setGeometry(QtCore.QRect(1580, 620, 131, 51))
        self.pushButton_readline.setObjectName("pushButton_readline")
        self.pushButton_clearallline = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clearallline.setGeometry(QtCore.QRect(1390, 620, 131, 51))
        self.pushButton_clearallline.setObjectName("pushButton_clearallline")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1762, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.actionbangzhu = QtWidgets.QAction(MainWindow)
        self.actionbangzhu.setObjectName("actionbangzhu")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu_2.addAction(self.action_2)
        self.menu_3.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget_CJ.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Studio"))
        self.pushButton_5.setText(_translate("MainWindow", "写字&画画"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "串口1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "串口2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "串口3"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_connection.setText(_translate("MainWindow", "连接"))
        self.pushButton_resetzero.setText(_translate("MainWindow", "归零"))
        self.pushButton_replace.setText(_translate("MainWindow", "复位"))
        self.pushButton_stop.setText(_translate("MainWindow", "急停"))
        self.pushButton_14.setText(_translate("MainWindow", "登录"))
        self.label_4.setText(_translate("MainWindow", "未登录"))
        self.pushButton_11.setText(_translate("MainWindow", "新建"))
        self.pushButton_10.setText(_translate("MainWindow", "打开"))
        self.pushButton_9.setText(_translate("MainWindow", "保存"))
        self.pushButton_8.setText(_translate("MainWindow", "另存为"))
        self.pushButton_7.setText(_translate("MainWindow", "开始"))
        self.pushButton_12.setText(_translate("MainWindow", "停止"))
        self.pushButton_13.setText(_translate("MainWindow", "设置"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
        self.groupBox.setTitle(_translate("MainWindow", "选项"))
        self.pushButton_15.setText(_translate("MainWindow", "清空"))
        self.pushButton_17.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_18.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_run_coordinate.setText(_translate("MainWindow", "运行"))
        self.label_Speed_name_coordinate.setText(_translate("MainWindow", "速度"))
        self.label_Speed_num_coordinate.setText(_translate("MainWindow", "25"))
        self.pushButton_speedsetting_coordinate.setText(_translate("MainWindow", "速度设置"))
        self.pushButton_zup.setText(_translate("MainWindow", "Z+"))
        self.pushButton_yup.setText(_translate("MainWindow", "Y+"))
        self.pushButton_ydown.setText(_translate("MainWindow", "Y-"))
        self.pushButton_xdown.setText(_translate("MainWindow", "X-"))
        self.pushButton_xup.setText(_translate("MainWindow", "X+"))
        self.pushButton_rup.setText(_translate("MainWindow", "R+"))
        self.label_x.setText(_translate("MainWindow", "X"))
        self.label_y.setText(_translate("MainWindow", "Y"))
        self.label_r.setText(_translate("MainWindow", "R"))
        self.pushButton_zdown.setText(_translate("MainWindow", "Z-"))
        self.pushButton_rdown.setText(_translate("MainWindow", "R-"))
        self.label_z.setText(_translate("MainWindow", "Z"))
        self.label_step_coordinate.setText(_translate("MainWindow", "步长"))
        self.tabWidget_CJ.setTabText(self.tabWidget_CJ.indexOf(self.tab), _translate("MainWindow", "坐标"))
        self.pushButton_run_joint.setText(_translate("MainWindow", "运行"))
        self.pushButton_J3down.setText(_translate("MainWindow", "J3-"))
        self.label_J2.setText(_translate("MainWindow", "J2"))
        self.label_J3.setText(_translate("MainWindow", "J3"))
        self.pushButton_J2down.setText(_translate("MainWindow", "J2-"))
        self.pushButton_J1up.setText(_translate("MainWindow", "J1+"))
        self.pushButton_J2up.setText(_translate("MainWindow", "J2+"))
        self.pushButton_J4down.setText(_translate("MainWindow", "J4-"))
        self.pushButton_J3up.setText(_translate("MainWindow", "J3+"))
        self.label_J1.setText(_translate("MainWindow", "J1"))
        self.label_J4.setText(_translate("MainWindow", "J4"))
        self.pushButton_J1down.setText(_translate("MainWindow", "J1-"))
        self.pushButton_J4up.setText(_translate("MainWindow", "J4+"))
        self.label_Speed_name_joint.setText(_translate("MainWindow", "速度"))
        self.label_Speed_num_joint.setText(_translate("MainWindow", "25"))
        self.pushButton_speedsetting_joint.setText(_translate("MainWindow", "速度设置"))
        self.label_step_joint.setText(_translate("MainWindow", "步长"))
        self.tabWidget_CJ.setTabText(self.tabWidget_CJ.indexOf(self.tab_2), _translate("MainWindow", "关节"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "写字&画画"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "延迟时间"))
        self.pushButton_readline.setText(_translate("MainWindow", "读取一行"))
        self.pushButton_clearallline.setText(_translate("MainWindow", "清屏"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.menu_4.setTitle(_translate("MainWindow", "工具"))
        self.actionbangzhu.setText(_translate("MainWindow", "bangzhu"))
        self.action.setText(_translate("MainWindow", "关于我们"))
        self.action_2.setText(_translate("MainWindow", "语言"))

